### ISSUE TITLE
Why the name is demo

### ISSUE THREAD

**Issue by deepakkum21** [NimishaR/microservices#1]
https://github.com/NimishaR/microservices/blob/003568ce916804de45e58c80b6d4e1966ea7e3e2/spring-mongodb-multi-tenant/src/main/java/com/nimisha/springmongodbmultitenant/config/MongoDbConfiguration.java#L18

**Comment by deepakkum21** [comment]
Please have a look at this and fix this for our comfort

**Comment by NimishaR** [comment]
Fixed
